"""AUTO-GENERATED by view-src/gen-chart-types.mjs — do not edit by hand.

Chart-type catalog derived from flint-chart's own template definitions so the
config enums and the LLM prompt stay in sync with the installed Flint version.
Regenerate with: cd view-src && npm run gen"""

from __future__ import annotations

VEGA_LITE_TYPES = (
    "Scatter Plot",
    "Regression",
    "Connected Scatter Plot",
    "Ranged Dot Plot",
    "Strip Plot",
    "Bar Chart",
    "Grouped Bar Chart",
    "Stacked Bar Chart",
    "Lollipop Chart",
    "Waterfall Chart",
    "Gantt Chart",
    "Bullet Chart",
    "Histogram",
    "Density Plot",
    "ECDF Plot",
    "Violin Plot",
    "Boxplot",
    "Pyramid Chart",
    "Candlestick Chart",
    "Line Chart",
    "Sparkline",
    "Bump Chart",
    "Slope Chart",
    "Area Chart",
    "Streamgraph",
    "Range Area Chart",
    "Pie Chart",
    "Rose Chart",
    "Radar Chart",
    "Heatmap",
    "Bar Table",
    "KPI Card",
    "Map",
    "Choropleth",
)

ECHARTS_TYPES = (
    "Scatter Plot",
    "Regression",
    "Connected Scatter Plot",
    "Ranged Dot Plot",
    "Boxplot",
    "Strip Plot",
    "Bar Chart",
    "Grouped Bar Chart",
    "Stacked Bar Chart",
    "Lollipop Chart",
    "Pyramid Chart",
    "Heatmap",
    "Calendar Heatmap",
    "Line Chart",
    "Bump Chart",
    "Slope Chart",
    "Area Chart",
    "Streamgraph",
    "Range Area Chart",
    "Pie Chart",
    "Funnel Chart",
    "Treemap",
    "Sunburst Chart",
    "Tree",
    "Histogram",
    "Density Plot",
    "ECDF Plot",
    "Parallel Coordinates",
    "Candlestick Chart",
    "Waterfall Chart",
    "Gantt Chart",
    "Bullet Chart",
    "Radar Chart",
    "Rose Chart",
    "Gauge Chart",
    "Sankey Diagram",
    "Network Graph",
)

CHARTJS_TYPES = (
    "Scatter Plot",
    "Connected Scatter Plot",
    "Bubble Chart",
    "Strip Plot",
    "Bar Chart",
    "Grouped Bar Chart",
    "Stacked Bar Chart",
    "Combo Chart",
    "Histogram",
    "Waterfall Chart",
    "Gantt Chart",
    "Line Chart",
    "Slope Chart",
    "Area Chart",
    "Range Area Chart",
    "ECDF Plot",
    "Pie Chart",
    "Doughnut Chart",
    "Radar Chart",
    "Rose Chart",
)

CHART_TYPES_BY_LIBRARY = {
    "vega-lite": VEGA_LITE_TYPES,
    "echarts": ECHARTS_TYPES,
    "chartjs": CHARTJS_TYPES,
}

CHART_CATALOG_MARKDOWN = r'''### Vega-Lite (library: "vega-lite")
- Scatter Plot — channels: x, y, color, size, shape, opacity, column, row
- Regression — channels: x, y, size, color, column, row
- Connected Scatter Plot — channels: x, y, order, color, detail, column, row
- Ranged Dot Plot — channels: x, y, color
- Strip Plot — channels: x, y, color, size, column, row
- Bar Chart — channels: x, y, color, group, opacity, column, row
- Grouped Bar Chart — channels: x, y, group, column, row
- Stacked Bar Chart — channels: x, y, color, column, row
- Lollipop Chart — channels: x, y, color, column, row
- Waterfall Chart — channels: x, y, color, column, row
- Gantt Chart — channels: y, x, x2, color, detail, column, row
- Bullet Chart — channels: y, x, goal, color, column, row
- Histogram — channels: x, color, column, row
- Density Plot — channels: x, color, column, row
- ECDF Plot — channels: x, color, detail, column, row
- Violin Plot — channels: x, y, color, row
- Boxplot — channels: x, y, color, opacity, column, row
- Pyramid Chart — channels: x, y, color
- Candlestick Chart — channels: x, open, high, low, close, column, row
- Line Chart — channels: x, y, color, strokeDash, detail, opacity, column, row
- Sparkline — channels: x, y, color, detail, row, column
- Bump Chart — channels: x, y, color, detail, column, row
- Slope Chart — channels: x, y, color, detail, column, row
- Area Chart — channels: x, y, color, opacity, column, row
- Streamgraph — channels: x, y, color, column, row
- Range Area Chart — channels: x, y, y2, color, column, row
- Pie Chart — channels: size, color, column, row
- Rose Chart — channels: x, y, color, column, row
- Radar Chart — channels: x, y, color, column, row
- Heatmap — channels: x, y, color, column, row
- Bar Table — channels: y, x, color, column, row
- KPI Card — channels: metric, value, goal
- Map — channels: longitude, latitude, color, size, opacity
- Choropleth — channels: id, color, detail

### ECharts (library: "echarts")
- Scatter Plot — channels: x, y, color, size, opacity, column, row
- Regression — channels: x, y, size, color, column, row
- Connected Scatter Plot — channels: x, y, order, color, detail, column, row
- Ranged Dot Plot — channels: x, y, color
- Boxplot — channels: x, y, color, opacity, column, row
- Strip Plot — channels: x, y, color, size, column, row
- Bar Chart — channels: x, y, color, opacity, column, row
- Grouped Bar Chart — channels: x, y, group, color, column, row
- Stacked Bar Chart — channels: x, y, color, column, row
- Lollipop Chart — channels: x, y, color, column, row
- Pyramid Chart — channels: x, y, color
- Heatmap — channels: x, y, color, column, row
- Calendar Heatmap — channels: x, color
- Line Chart — channels: x, y, color, opacity, column, row
- Bump Chart — channels: x, y, color, detail, column, row
- Slope Chart — channels: x, y, color, detail, column, row
- Area Chart — channels: x, y, color, opacity, column, row
- Streamgraph — channels: x, y, color, column, row
- Range Area Chart — channels: x, y, y2, color, column, row
- Pie Chart — channels: size, color, column, row
- Funnel Chart — channels: y, size
- Treemap — channels: color, size, detail
- Sunburst Chart — channels: color, size, detail, group
- Tree — channels: color, detail, size
- Histogram — channels: x, color, column, row
- Density Plot — channels: x, color, column, row
- ECDF Plot — channels: x, color, detail, column, row
- Parallel Coordinates — channels: color, detail
- Candlestick Chart — channels: x, open, high, low, close, column, row
- Waterfall Chart — channels: x, y, color, column, row
- Gantt Chart — channels: y, x, x2, color, detail, column, row
- Bullet Chart — channels: y, x, goal, color, column, row
- Radar Chart — channels: x, y, color, column, row
- Rose Chart — channels: x, y, color, column, row
- Gauge Chart — channels: size, column
- Sankey Diagram — channels: x, y, size
- Network Graph — channels: x, y, size

### Chart.js (library: "chartjs")
- Scatter Plot — channels: x, y, color, size, opacity, column, row
- Connected Scatter Plot — channels: x, y, order, color, detail, column, row
- Bubble Chart — channels: x, y, size, color, opacity, column, row
- Strip Plot — channels: x, y, color, size, column, row
- Bar Chart — channels: x, y, color, opacity, column, row
- Grouped Bar Chart — channels: x, y, group, color, column, row
- Stacked Bar Chart — channels: x, y, color, column, row
- Combo Chart — channels: x, y, column, row
- Histogram — channels: x, color, column, row
- Waterfall Chart — channels: x, y, color, column, row
- Gantt Chart — channels: y, x, x2, color, column, row
- Line Chart — channels: x, y, color, opacity, column, row
- Slope Chart — channels: x, y, color, detail, column, row
- Area Chart — channels: x, y, color, opacity, column, row
- Range Area Chart — channels: x, y, y2, color, column, row
- ECDF Plot — channels: x, color, detail, column, row
- Pie Chart — channels: size, color, column, row
- Doughnut Chart — channels: size, color, column, row
- Radar Chart — channels: x, y, color, column, row
- Rose Chart — channels: x, y, color, column, row
'''
